# Generated by Django 5.2.4 on 2025-08-08 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.chatbot'),
        ),
    ]
