# Generated by Django 5.2.4 on 2025-08-08 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_services_service_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='service_owner',
            new_name='chatbot_service',
        ),
    ]
