# Generated by Django 5.2.4 on 2025-08-08 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_service_owner_services_chatbot_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='chatbot_service',
        ),
        migrations.AddField(
            model_name='services',
            name='chatbot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_service', to='users.chatbot'),
            preserve_default=False,
        ),
    ]
