# Generated by Django 5.2.4 on 2025-08-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_services_chatbot_service_services_chatbot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELED', 'Canceled'), ('RESCHEDULED', 'Rescheduled')], default='ACTIVE', max_length=28),
        ),
    ]
