# Generated by Django 5.2.4 on 2025-08-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_appointments_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='Description_of_service',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
