# Generated by Django 5.2.4 on 2025-08-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_services_description_of_service_alter_chatbot_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='Description_of_service',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
