# Generated by Django 5.2.4 on 2025-08-23 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_services_chatbot_services_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='diccount',
        ),
        migrations.RemoveField(
            model_name='services',
            name='discount_deadline',
        ),
        migrations.RemoveField(
            model_name='services',
            name='discount_price',
        ),
        migrations.AlterField(
            model_name='services',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=28),
        ),
        migrations.CreateModel(
            name='service_discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_deadline', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='INACTIVE', max_length=28)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_discount', to='users.services')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
