# Generated by Django 5.2.4 on 2025-08-24 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_services_diccount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_avalablity',
            name='from_time',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(code='invalid_time', message='Enter a valid time in HH:MM format (e.g., 14:30).', regex='^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$')]),
        ),
        migrations.AlterField(
            model_name='user_avalablity',
            name='to_time',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(code='invalid_time', message='Enter a valid time in HH:MM format (e.g., 14:30).', regex='^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$')]),
        ),
    ]
