# Generated by Django 5.2.4 on 2025-08-26 04:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_avalablity_from_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_avalablity',
            name='from_time',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(code='invalid_time', message='Enter a valid time in hh:mm AM/PM format (e.g., 02:30 PM).', regex='^((0?[1-9]|1[0-2]):[0-5][0-9]\\s?(?i)(am|pm))$')]),
        ),
        migrations.AlterField(
            model_name='user_avalablity',
            name='to_time',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(code='invalid_time', message='Enter a valid time in hh:mm AM/PM format (e.g., 02:30 PM).', regex='^((0?[1-9]|1[0-2]):[0-5][0-9]\\s?(?i)(am|pm))$')]),
        ),
    ]
