# Generated by Django 5.2.4 on 2025-08-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_avalablity_from_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_avalablity',
            name='day',
            field=models.JSONField(),
        ),
    ]
