# Generated by Django 5.2.4 on 2025-08-26 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_avalablity_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_avalablity',
        ),
    ]
