# Generated by Django 5.2.4 on 2025-08-26 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_avalablity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_avalablity',
            old_name='day',
            new_name='days',
        ),
    ]
