# Generated by Django 5.2.4 on 2025-08-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_rename_day_user_avalablity_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_avalablity',
            name='time_slot_duration',
            field=models.IntegerField(default=30, help_text='Duration in minutes'),
        ),
    ]
