# Generated by Django 5.2.4 on 2025-08-26 11:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_appointments_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_unavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reason', models.CharField(max_length=128)),
                ('from_date', models.DateField()),
                ('from_time', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(code='invalid_time', message='Enter a valid time in hh:mm AM/PM format (e.g., 02:30 PM).', regex='(?i)^((0?[1-9]|1[0-2]):[0-5][0-9]\\s?(am|pm))$')])),
                ('to_date', models.DateField()),
                ('to_time', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(code='invalid_time', message='Enter a valid time in hh:mm AM/PM format (e.g., 02:30 PM).', regex='(?i)^((0?[1-9]|1[0-2]):[0-5][0-9]\\s?(am|pm))$')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_unavalablit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
