# Generated by Django 5.2.4 on 2025-08-28 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='customer',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='Description_of_service',
            new_name='service_description',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='service',
            new_name='service_name',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='contact',
        ),
        migrations.AddField(
            model_name='appointments',
            name='contact_number',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AddField(
            model_name='appointments',
            name='customer_email',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='time',
            field=models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator(code='invalid_time', message='Enter a valid time in hh:mm AM/PM format (e.g., 02:30 PM).', regex='(?i)^((0?[1-9]|1[0-2]):[0-5][0-9]\\s?(am|pm))$')]),
        ),
    ]
