# Generated by Django 5.2.4 on 2025-09-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_rename_service_name_appointments_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='cancel_reason',
            field=models.TextField(blank=True),
        ),
    ]
