# Generated by Django 5.2.4 on 2025-09-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_appointments_cancel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='reschedule',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointments',
            name='reschedule_reason',
            field=models.TextField(blank=True),
        ),
    ]
