# Generated by Django 5.2.4 on 2025-09-04 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_adminnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminnotification',
            name='user',
        ),
    ]
