# Generated by Django 5.2.4 on 2025-08-08 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_chatbot_services_appointments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbot',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='services',
            name='service_owner',
        ),
        migrations.DeleteModel(
            name='Appointments',
        ),
        migrations.DeleteModel(
            name='Chatbot',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
