# Generated by Django 5.2.4 on 2025-08-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
