# Generated by Django 5.2.4 on 2025-08-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_is_subscription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_subscription',
            new_name='is_subscribed',
        ),
        migrations.AddField(
            model_name='customuser',
            name='subsciption_expires_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_status',
            field=models.CharField(default='freemium', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
