# Generated by Django 5.2.4 on 2025-08-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_is_subscription_customuser_is_subscribed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('HOLD', 'Hold')], default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subscription_status',
            field=models.CharField(max_length=100),
        ),
    ]
