# Generated by Django 5.2.4 on 2025-08-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscription_status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
