# Generated by Django 5.2.4 on 2025-09-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_subscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('HOLD', 'Hold')], default='HOLD', max_length=10),
        ),
    ]
